version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:current
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD

jobs:
  build udagram-api-feed:
    branches:
      only:
        main
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build docker image"
          command: docker build -t saegeroliver/udagram-api-feed:latest ./udagram-api-feed

      - run:
          name: "Login to the hub"
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: "Push docker image to hub"
          command: docker push $DOCKERHUB_USER/udagram-api-feed:latest
  build udagram-api-user:
    branches:
      only:
        main
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build docker image"
          command: docker build -t saegeroliver/udagram-api-user:latest ./udagram-api-user

      - run:
          name: "Login to the hub"
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: "Push docker image to hub"
          command: docker push $DOCKERHUB_USER/udagram-api-user:latest
  build udagram-frontend:
    branches:
      only:
        main
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build docker image"
          command: docker build -t saegeroliver/udagram-frontend:latest ./udagram-frontend

      - run:
          name: "Login to the hub"
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: "Push docker image to hub"
          command: docker push $DOCKERHUB_USER/udagram-frontend:latest
  build udagram-reverseproxy:
    branches:
      only:
        main
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: "Build docker image"
          command: docker build -t saegeroliver/udagram-reverseproxy:latest ./udagram-reverseproxy

      - run:
          name: "Login to the hub"
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

      - run:
          name: "Push docker image to hub"
          command: docker push $DOCKERHUB_USER/udagram-reverseproxy:latest


workflows:
  build udagram:
    jobs:
      - build udagram-api-feed
      - build udagram-api-user
      - build udagram-frontend
      - build udagram-reverseproxy